export enum IconSet {
  MATERIAL = 'material',
  MATERIAL_COMMUNITY = 'material-community',
  FONT_AWESOME = 'font-awesome',
  OCTICON = 'octicon',
  IONICON = 'ionicon',
  FOUNDATION = 'foundation',
  EVILICON = 'evilicon',
  SIMPLE_LINE_ICON = 'simple-line-icon',
  ZOCIAL = 'zocial',
  ENTYPO = 'entypo',
  FEATHER = 'feather',
  ANTDESIGN = 'antdesign',
  FONT_AWESOME_5 = 'font-awesome-5',
  FONT_AWESOME_5_PRO = 'font-awesome-5-pro',
  FONT_AWESOME_5_PRO_LIGHT = 'font-awesome-5-pro-light',
  FONT_AWESOME_5_PRO_SOLID = 'font-awesome-5-pro-solid',
  FONT_AWESOME_5_PRO_BRAND = 'font-awesome-5-pro-brand',
}
